{{ if .Values.service.ingress.tlsEnabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "cluster-info.fullname" . }}-tls"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "cluster-info.labels" . | indent 4 }}
  annotations:
    {{- if .Values.service.ingress.kubeLego }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    kubernetes.io/ingress.class: "{{ .Values.service.ingress.class}}"
    external-dns.alpha.kubernetes.io/hostname: "{{ include "cluster-info.fqdn" . }}"
    {{- range $key, $value := .Values.service.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: "{{ include "cluster-info.fqdn" . }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "cluster-info.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
  tls:
  - hosts:
    - {{ include "cluster-info.fqdn" . }}
    secretName: {{ default ( printf "%s-tls" .Release.Namespace ) .Values.service.ingress.tlsSecretName }}
{{ end }}
