apiVersion: v1
kind: Service
metadata:
  name: {{ template "cluster-info.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "cluster-info.labels" . | indent 4 }}
  {{- if and (.Values.service.type) (.Values.subDomain) }}
  annotations:
      external-dns.alpha.kubernetes.io/hostname: "{{ include "cluster-info.fqdn" . }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ .Chart.Name }}
